### ISSUE TITLE
Add create tour activity to create a tour.

### ISSUE THREAD

**Issue by FrancisMengx** [wzmame/pictour#7]
Add activity to create a tour. Design the user interface and connect it with the parse backend storage.

[Mockup of the new-tour activity](https://www.fluidui.com/editor/live/preview/p_Llo6CBk71dl34aegf4O0yK1vT12i5rzy)

Acceptance criteria:
 - Has create tour activity layout.
 - Layout needs to have basic input field for user to input basic information of the tour
 - Layout needs to have a button to go to the next step to create a spot of the tour.
 - Layout needs to have a button to indicate that the user is done creating a tour.

**Comment by jeffbmartinez** [comment]
Duplicate of https://github.com/wzmame/pictour/issues/13
