### ISSUE TITLE
Hook up homepage activity to tour-creation activity

### ISSUE THREAD

**Issue by FrancisMengx** [wzmame/pictour#9]
After the home page (https://github.com/wzmame/pictour/issues/12) and tour-creation (https://github.com/wzmame/pictour/issues/13) activities are complete, we need to hook them up.

When the new tour is created, it should show up in the list of available tours in the homepage.

Here is the [interactive project mockup](https://www.fluidui.com/editor/live/preview/p_Llo6CBk71dl34aegf4O0yK1vT12i5rzy).

Acceptance criteria:
  - [x] Clicking new-tour button on home page takes you to the tour creation activity
  - [x] Clicking "done" in create-tour activity takes you back to home page

**Comment by jeffbmartinez** [comment]
Added the part about going back to the homepage from the create-tour activity. Reopening.
